name: Update README
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with dynamic information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull in cupfullofcode.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://cupfullofcode.com/index.xml"

      - name: Update GitHub activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
